on: [push]

name: CI for the 'invert' library

jobs:
  build:
    name: Build and test the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - '9.0.1'
          - '8.10.3'
          - '8.8.4'
          - '8.6.5'

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Build
        run: cabal build
      - name: Test
        run: cabal test
